export enum ValidateArticleError {
    EMPTY_MAIN = 'EMPTY MAIN',
    INCORRECT_ARTICLE_TYPE = 'INCORRECT ARTICLE TYPE',
    EMPTY_BLOCKS = 'EMPTY BLOCKS',
    NO_BLOCKS = 'NO BLOCKS',
    NO_DATA = 'NO DATA',
    SERVER_ERROR = 'SERVER ERROR',
}
